version: "3"
services:
  postgres:
    image: postgres:16.0-alpine3.18
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_USERNAME}
      POSTGRES_DB: ${DB_PASSWORD}
    ports:
      - 5444:5432
    volumes:
      - db:/var/lib/postgres

  nestjs-app:
    depends_on:
      - postgres
    container_name: polytrade-nestjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    # environment:
    #   DATABASE_URL: postgres://postgres:posetgres@localhost:5432/postgres

volumes: 
  db: